### PR TITLE
Fix #5631

### LINKED ISSUE #5631: Upload cover picture does not work when using subfolder
Uploaded cover picture path does not contain the `relative_path`.

### PR DESCRIPTION
**Pull request by pitaj**
- Fix profile covers not working with subfolders
- Remove relative_path from the paths saved in the database so they're more portable

### CODE REVIEW

File: src/controllers/accounts/helpers.js [hunk 1]
```diff
@@ -144,7 +145,7 @@ helpers.getUserDataByUserSlug = function (userslug, callerUID, callback) {
 			userData.birthday = validator.escape(String(userData.birthday || ''));
 			userData.moderationNote = validator.escape(String(userData.moderationNote || ''));
 
-			userData['cover:url'] = userData['cover:url'] || require('../../coverPhoto').getDefaultProfileCover(userData.uid);
+			userData['cover:url'] = (nconf.get('relative_path') + userData['cover:url']) || require('../../coverPhoto').getDefaultProfileCover(userData.uid);
```
Comment (barisusakli) [inline src/controllers/accounts/helpers.js]: this will cause the `userData['cover:url']` to be equal to `nconf.get('relative_path')` if `userData['cover:url']` is an empty string.
