### PR TITLE
Filter out any undefined events

### LINKED ISSUE #5130: Events page doesn't load
I was encountering an error on the latest v1.x.x branch (a9d69c4779b25c80f00cece417bf7fcb4d10d18b) where the Advanced -> Events page was crashing the whole forum. I don't know how an undefined event is getting in the database, I just upgraded from 1.2.0 to 1.2.1 (but this could have happened before then)

Mongo 3.0.7 on OSX

### PR DESCRIPTION
**Pull request by bdharrington7**
Fixes #5130

Happy #hacktoberfest

### CODE REVIEW

File: src/events.js [hunk 1]
```diff
@@ -53,11 +53,14 @@ var utils = require('../public/src/utils');
 				addUserData(eventsData, 'targetUid', 'targetUser', next);
 			},
 			function (eventsData, next) {
-				eventsData.forEach(function (event) {
+				eventsData.filter(function (element) {
```
Comment (bdharrington7) [inline src/events.js]: Cool, didn't know that one before, thanks!
